Couldnt upload profile image on production server
The problem was that the old profile image had to be deleted from database, before the new profile image was added.
-> Delete old profile image, before adding a new one.

Error message:
IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`django_stylematch`.`accounts_userprofile`, CONSTRAINT `profile_image_cropped_id_refs_id_642e3627c966e98e` FOREIGN KEY (`profile_image_cropped_id`) REFERENCES `accounts_profileimage` (`id`))')